### ISSUE TITLE
provide code snippet for key event location explicitly in SARIF output

### ISSUE THREAD

**Issue by kdudka** [csutils/csdiff#124]
As originally reported by Mert Bugra Bicak, the SARIF writer in csdiff should provide code snippet for key event location explicitly, as in this example: https://github.com/DefectDojo/django-DefectDojo/blob/master/unittests/scans/sarif/gitleaks_7.5.0.sarif  so that the SARIF parser in DefectDojo can process them.

**Comment by kdudka** [comment]
@mertbugrabicak Could you please try csdiff packages from the following COPR and check whether they produce the expected output?  https://copr.fedorainfracloud.org/coprs/packit/csutils-csdiff-127/

**Comment by mertbugrabicak** [comment]
Hi @kdudka , just checked and it seems to be working, thanks! Both the CWEs and the code snippet are included in the imported results now

I only have a tiny thing to point out: Before concatenating the snippet lines like LINE1\nLINE2\n... can we strip each line of their leading spaces? I think when DefectDojo imports that snippet text, it seems to lose the leading spaces in the first line, and it causes a right-shift in the continuing lines, causing it to look a little mis-aligned:

For example, in DefectDojo it looks like
1269|
  1270|
  1271|->
  1272|
  1273|

Where if we strip each line before concatenating, it can look align as below:
1269|
1270|
1271|->
1272|
1273|

This is purely aesthetics of course

**Comment by mertbugrabicak** [comment]
Oops github also seems to strip the leading spaces from my example :)

**Comment by kdudka** [comment]
@mertbugrabicak Thank you for testing it!

> Before concatenating the snippet lines like LINE1\nLINE2\n... can we strip each line of their leading spaces?

The problem is that it would still be misaligned if the code snippet was spread across line numbers with different count of digits:
```
98|
99|
100|->
101|
102|
```

I am wondering whether we could prepend some special character to prevent DefectDojo from stripping the leading white spaces?

**Comment by mertbugrabicak** [comment]
Oh I hadn't thought of those types of cases, that's true. Yeah, I think that might work

**Comment by kdudka** [comment]
I attempted to fix this in commit de3c5c97406e4889c07ceb53c4fc714bd84cb351.  @mertbugrabicak Could you please update to `csdiff-3.0.1.20230420.085832.gde3c5c9.pr_127-1` and check whether it works any better?

**Comment by mertbugrabicak** [comment]
@kdudka Just checked and it looks great, fixes the problem, thank you!

**Comment by kdudka** [comment]
Perfect.  Thank you for testing it!
