### ISSUE TITLE
parser-json-cov: add support for the v10 JSON format of Coverity

### ISSUE THREAD

**Issue by kdudka** [csutils/csdiff#131]
Since commit b78b49f61fc24998b4bfe4286852148708c94f9e we are able to read CWEs from the JSON format of Coverity.  We should check whether we can get more information out of the format produced by `cov-format-errors --json-output-v10 ...`, which is the recommended export format in Coverity 2023.3.0.

**Comment by jperezdealgaba** [comment]
After doing the research for this. We added the support for the new `column` field under this [commit](https://github.com/csutils/csdiff/commit/1461144e18a2fde05239116343f987f0e0381f7c) and we also added the [tests](https://github.com/csutils/csdiff/commit/ac8946dd7149676e0ad0ddf61c02438dfe442e23).

Apart from that, there aren't significant changes in the v10 JSON format of coverity.
This issue can be closed.

**Comment by kdudka** [comment]
@jperezdealgaba Thanks!  Closing...
