### ISSUE TITLE
Support advanced ShellCheck rule descriptions for the SARIF format

### ISSUE THREAD

**Issue by lzaoral** [csutils/csdiff#54]
With this, we could add e.g. an additional description of the given ShellCheck rule as we do in the HTML writer.

Additional information: https://github.com/microsoft/sarif-tutorials/blob/main/docs/2-Basics.md#rule-metadata

**Comment by kdudka** [comment]
I realized that we already have code that encodes help text in the SARIF format: https://github.com/csutils/csdiff/blob/57f06354756d783ab76a588c2faefff9fd43303e/src/json-writer.cc#L192-L197
It should be not so difficult to extend it for tool-specific help text.

**Comment by jamacku** [comment]
Thank you for working on it!
