### ISSUE TITLE
SARIF: Add option to generate `tool` property based on provided input

### ISSUE THREAD

**Issue by jamacku** [csutils/csdiff#82]
In Differential ShellCheck, I'm using the following [`sed` to replace `tool: csdiff` with `tool: ShellCheck`](https://github.com/redhat-plumbers-in-action/differential-shellcheck/blob/7f1eca2e270258fd24ed0fb39de1dbc3d705c017/src/index.sh#L111):

```sh
sed 's/"csdiff"/"ShellCheck"/' >> output.sarif && uploadSARIF
```

Without `sed`, GitHub says that defects were reported by `csdiff` where in fact, `csdiff` only produced them, and the tool that reported them is ShellCheck. Using `sed` works, but it certainly has some flaws.

It would be nice to have some option, e.g. `--tool`, to specify tool names that should be put into the `tool` property in generated SARIF.

**Comment by kdudka** [comment]
I have submitted pull request #85 to address this.  The following test shows how the new option can be used for what was requested: https://github.com/csutils/csdiff/pull/85/files#diff-7f74d0b4b6bef80a717fdd3886f6537cab62c81edeb106a79dffd317e3aa2bf2
