### ISSUE TITLE
SARIF: Please add support for `fingerprints` in SARIF format :feet: 

### ISSUE THREAD

**Issue by jamacku** [csutils/csdiff#98]
Fingerprints could be beneficial when used with GitHub and for a general comparison of scan results.

Documentation of `fingerprints` property: [link](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317654)

GitHub SARIF Documentation: [link](https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning#providing-data-to-track-code-scanning-alerts-across-runs)

**Comment by kdudka** [comment]
My initial thought was to compute a hash from all the data that are matched in `DefLookup::lookup()`.  The problem is that `DefLookup` is able to count occurrences of defects with equal fields (which would result in identical hashes) whereas GitHub would see all of them as a single defect.  This would not work well when a new instance of defect with previously seen fingerprint was introduced in an update.

**Comment by jamacku** [comment]
Here is scala example of creating `partialFingerprints` from [`codacy/codacy-analysis-cli`](https://github.com/codacy/codacy-analysis-cli/blob/80c8baecbfea050feb5cee184051b996cdd7fed3/cli/src/main/scala/com/codacy/analysis/cli/formatter/Sarif.scala#L168):

```scala
partialFingerprints = SarifReport.PartialFingerprints("1", generatePrimaryLocationHash(issue, fileContents)))

// ...

final case class PartialFingerprints(primaryLocationStartColumnFingerprint: String, primaryLocationLineHash: String)
```

It seems they are counting only with line numbers and with the hash of line content.

**Comment by kdudka** [comment]
@jamacku The actual fingerprint computation is here: https://github.com/codacy/codacy-analysis-cli/blob/80c8baecbfea050feb5cee184051b996cdd7fed3/cli/src/main/scala/com/codacy/analysis/cli/formatter/Sarif.scala#L192

They compute MD5 hash of a string concatenated from  `fileName`, `patternId`, and `lineContentsWithoutSpaces`.

**Comment by jamacku** [comment]
Here is an example of how fingerprints are handled by [`github/codeql-action`](https://github.com/github/codeql-action) - [code](https://github.com/github/codeql-action/blob/bb28e7e59e2ad6c1e5400e671795b2fa1b2fca6f/src/fingerprints.ts#L250-L309)

And also one comment how it works:

- https://github.com/github/codeql-action/issues/986#issuecomment-1171269954

**Comment by kdudka** [comment]
`codeql-action` seems to hash context lines with their own Ad-Hoc implemented hash function: https://github.com/github/codeql-action/blob/bb28e7e59e2ad6c1e5400e671795b2fa1b2fca6f/lib/fingerprints.js#L49
